In [1]:
import numpy as np
import pandas as pd

# Deliveries Dataframe

In [2]:
deliveries_df = pd.read_csv('ipl_ball_by_ball.csv', low_memory = False)
matches_df = pd.read_csv('ipl_matches.csv')

In [3]:
deliveries_df

,match_id,date,season,venue,city,innings,batting_team,bowling_team,over,ball_in_over,...,wicket_kind,match_winner,toss_winner,toss_decision,team1,team2,is_powerplay,is_middle_overs,is_death_overs,batting_team_won
0,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,1,...,NaN,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore,1,0,0,1
1,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,2,...,NaN,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore,1,0,0,1
2,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,3,...,NaN,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore,1,0,0,1
3,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,4,...,NaN,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore,1,0,0,1
4,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bangalore,0,5,...,NaN,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,Royal Challengers Bangalore,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,2,...,NaN,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,Sunrisers Hyderabad,0,0,1,0
288222,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,3,...,run out,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,Sunrisers Hyderabad,0,0,1,0
288223,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,4,...,NaN,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,Sunrisers Hyderabad,0,0,1,0
288224,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,5,...,NaN,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,Sunrisers Hyderabad,0,0,1,0
288225,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bangalore,Sunrisers Hyderabad,19,6,...,NaN,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,Sunrisers Hyderabad,0,0,1,0

In [4]:
deliveries_df.dtypes

match_id              int64
date                 object
season               object
venue                object
city                 object
innings               int64
batting_team         object
bowling_team         object
over                  int64
ball_in_over          int64
ball_number           int64
batter               object
bowler               object
non_striker          object
batter_runs           int64
extra_runs            int64
total_runs            int64
wides                 int64
noballs               int64
byes                  int64
legbyes               int64
penalty               int64
is_wicket             int64
wicket_player_out    object
wicket_kind          object
match_winner         object
toss_winner          object
toss_decision        object
team1                object
team2                object
is_powerplay          int64
is_middle_overs       int64
is_death_overs        int64
batting_team_won      int64
dtype: object

In [5]:
deliveries_df['date'].min()

'2008-04-18'

In [6]:
deliveries_df['date'].max()

'2026-05-01'

In [7]:
deliveries_df['season'].dtype

dtype('O')

In [8]:
# O -> String Conversion
deliveries_df['season'] = deliveries_df['season'].astype('string')

# Season Mapping
season_mapping = {
    '2007/08':'2008',
    '2009/10':'2010',
    '2020/21':'2020'
}

# Replacing with data
deliveries_df['season'] = deliveries_df['season'].replace(season_mapping)

# Removing leftover spaces
deliveries_df['season'] = deliveries_df['season'].str.strip()

# String -> Int Conversion
deliveries_df['season'] = pd.to_numeric(deliveries_df['season'], errors='coerce').astype('Int64')

In [9]:
print(sorted(deliveries_df['season'].unique()))

[np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

In [10]:
# Converting date column to datetime 
deliveries_df['date'] = pd.to_datetime(deliveries_df['date'], errors='coerce')

In [11]:
summary = deliveries_df.groupby('season')['date'].agg(['min','max','count']).sort_index()
summary['calender_years'] = deliveries_df.groupby('season')['date'].apply(lambda x: sorted(x.dt.year.dropna().unique().astype(int)))
summary

              min        max  count calender_years
season
2008   2008-04-18 2008-06-01  13489         [2008]
2009   2009-04-18 2009-05-24  13606         [2009]
2010   2010-03-12 2010-04-25  14498         [2010]
2011   2011-04-08 2011-05-28  17013         [2011]
2012   2012-04-04 2012-05-27  17767         [2012]
2013   2013-04-03 2013-05-26  18177         [2013]
2014   2014-04-16 2014-06-01  14300         [2014]
2015   2015-04-08 2015-05-24  13652         [2015]
2016   2016-04-09 2016-05-29  14096         [2016]
2017   2017-04-05 2017-05-21  13862         [2017]
2018   2018-04-07 2018-05-27  14286         [2018]
2019   2019-03-23 2019-05-12  14312         [2019]
2020   2020-09-19 2020-11-10  14559         [2020]
2021   2021-04-09 2021-10-15  14425         [2021]
2022   2022-03-26 2022-05-29  17912         [2022]
2023   2023-03-31 2023-05-29  17863         [2023]
2024   2024-03-22 2024-05-26  17103         [2024]
2025   2025-03-22 2025-06-03  17285         [2025]
2026   2026-03-28 2026-05-01  10021         [2026]

In [12]:
# Converting all object dtype -> string
object_col = deliveries_df.select_dtypes(include=['object']).columns
deliveries_df[object_col] = deliveries_df[object_col].astype('string')

In [13]:
deliveries_df.dtypes

match_id                      int64
date                 datetime64[ns]
season                        Int64
venue                string[python]
city                 string[python]
innings                       int64
batting_team         string[python]
bowling_team         string[python]
over                          int64
ball_in_over                  int64
ball_number                   int64
batter               string[python]
bowler               string[python]
non_striker          string[python]
batter_runs                   int64
extra_runs                    int64
total_runs                    int64
wides                         int64
noballs                       int64
byes                          int64
legbyes                       int64
penalty                       int64
is_wicket                     int64
wicket_player_out    string[python]
wicket_kind          string[python]
match_winner         string[python]
toss_winner          string[python]
toss_decision        string[python]
team1                string[python]
team2                string[python]
is_powerplay                  int64
is_middle_overs               int64
is_death_overs                int64
batting_team_won              int64
dtype: object

In [14]:
# Missing values per column
missing_counts = deliveries_df.isna().sum()
missing_counts[missing_counts>0]

city                  12397
wicket_player_out    273886
wicket_kind          273886
match_winner           4980
dtype: int64

In [15]:
# Missing cities along with season column
missing_cities = deliveries_df[deliveries_df['city'].isna()][['venue','city']]
missing_cities.drop_duplicates()

                                     venue  city
42704  Dubai International Cricket Stadium  <NA>
43165              Sharjah Cricket Stadium  <NA>

In [16]:
# Filling the missing city with venue column 
first_word_of_venue = deliveries_df['venue'].str.split().str[0]
deliveries_df['city'] = np.where(deliveries_df['city'].isna(), first_word_of_venue, deliveries_df['city'])

In [17]:
# Verifying after filling 
print(deliveries_df['city'].isna().sum())

0

In [18]:
deliveries_df['wicket_player_out']

0              <NA>
1              <NA>
2              <NA>
3              <NA>
4              <NA>
            ...
288221         <NA>
288222    CJ Jordan
288223         <NA>
288224         <NA>
288225         <NA>
Name: wicket_player_out, Length: 288226, dtype: string

In [19]:
deliveries_df['wicket_kind']

0            <NA>
1            <NA>
2            <NA>
3            <NA>
4            <NA>
           ...
288221       <NA>
288222    run out
288223       <NA>
288224       <NA>
288225       <NA>
Name: wicket_kind, Length: 288226, dtype: string

In [20]:
# There's no such record of player being out and not given out
inconsistent_data = deliveries_df[deliveries_df['wicket_kind'].notna() & deliveries_df['wicket_player_out'].isna()]
print(len(inconsistent_data))
print(inconsistent_data[['wicket_kind','wicket_player_out']])

0
Empty DataFrame
Columns: [wicket_kind, wicket_player_out]
Index: []

In [21]:
# Filling dismissal data
deliveries_df['wicket_player_out'] = deliveries_df['wicket_player_out'].fillna('None')
deliveries_df['wicket_kind'] = deliveries_df['wicket_kind'].fillna('None')

In [22]:
# Verifying for dismissal data
print(deliveries_df['wicket_player_out'].isna().sum())
print(deliveries_df['wicket_kind'].isna().sum())

0
0

In [23]:
# Handling Match Winner Column 
deliveries_df['match_winner']

0         Sunrisers Hyderabad
1         Sunrisers Hyderabad
2         Sunrisers Hyderabad
3         Sunrisers Hyderabad
4         Sunrisers Hyderabad
                 ...
288221    Sunrisers Hyderabad
288222    Sunrisers Hyderabad
288223    Sunrisers Hyderabad
288224    Sunrisers Hyderabad
288225    Sunrisers Hyderabad
Name: match_winner, Length: 288226, dtype: string

In [24]:
# Clean match_winner column
deliveries_df['match_winner'] = deliveries_df['match_winner'].fillna('No Result')

In [25]:
# Verifying match_winner column
print(deliveries_df['match_winner'].isna().sum())

0

In [26]:
team_mapping = {
    'Deccan Chargers':'Sunrisers Hyderabad',
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab':'Punjab Kings',
    'Rising Pune Supergiants':'Rising Pune Supergiant',
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru'
}

team_col = ['batting_team','bowling_team','match_winner','toss_winner','team1','team2']

for col in team_col:
    if col in deliveries_df.columns:
        deliveries_df[col] = deliveries_df[col].astype(str).str.strip()
        deliveries_df[col] = deliveries_df[col].replace(team_mapping)

In [45]:
# Clean Deliveries Dataframe
deliveries_df.to_csv('ipl_deliveries_cleaned.csv', index = False)

# Matches Dataframe

In [27]:
matches_df

,match_id,date,city,venue,team1,team2,toss_winner,toss_decision,winner,result_type,player_of_match,season,event_name,match_type,gender,overs,balls_per_over,team1_won,toss_winner_won
0,1082591,2017-04-05,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,"['by', 'winner']",Yuvraj Singh,2017,Indian Premier League,T20,male,20,6,1,0
1,1082592,2017-04-06,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,Mumbai Indians,Rising Pune Supergiant,field,Rising Pune Supergiant,"['by', 'winner']",SPD Smith,2017,Indian Premier League,T20,male,20,6,1,1
2,1082593,2017-04-07,Rajkot,Saurashtra Cricket Association Stadium,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,"['winner', 'by']",CA Lynn,2017,Indian Premier League,T20,male,20,6,0,1
3,1082594,2017-04-08,Indore,Holkar Cricket Stadium,Kings XI Punjab,Rising Pune Supergiant,Kings XI Punjab,field,Kings XI Punjab,"['by', 'winner']",GJ Maxwell,2017,Indian Premier League,T20,male,20,6,1,1
4,1082595,2017-04-08,Bengaluru,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,"['winner', 'by']",KM Jadhav,2017,Indian Premier League,T20,male,20,6,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,981011,2016-05-22,Raipur,Shaheed Veer Narayan Singh International Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,"['by', 'winner']",V Kohli,2016,Indian Premier League,T20,male,20,6,0,1
1208,981013,2016-05-24,Bangalore,M Chinnaswamy Stadium,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,"['by', 'winner']",AB de Villiers,2016,Indian Premier League,T20,male,20,6,0,1
1209,981015,2016-05-25,Delhi,Feroz Shah Kotla,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Sunrisers Hyderabad,"['by', 'winner']",MC Henriques,2016,Indian Premier League,T20,male,20,6,1,0
1210,981017,2016-05-27,Delhi,Feroz Shah Kotla,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,"['by', 'winner']",DA Warner,2016,Indian Premier League,T20,male,20,6,0,1
1211,981019,2016-05-29,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,"['by', 'winner']",BCJ Cutting,2016,Indian Premier League,T20,male,20,6,0,1

In [28]:
matches_df.dtypes

match_id            int64
date               object
city               object
venue              object
team1              object
team2              object
toss_winner        object
toss_decision      object
winner             object
result_type        object
player_of_match    object
season             object
event_name         object
match_type         object
gender             object
overs               int64
balls_per_over      int64
team1_won           int64
toss_winner_won     int64
dtype: object

In [29]:
matches_df['season'].unique()

array(['2017', '2018', '2019', '2020/21', '2021', '2022', '2023', '2024',
       '2025', '2026', '2007/08', '2009', '2009/10', '2011', '2012',
       '2013', '2014', '2015', '2016'], dtype=object)

In [30]:
matches_df['date'].min()

'2008-04-18'

In [31]:
matches_df['date'].max()

'2026-05-01'

In [32]:
# O -> String Conversion
matches_df['season'] = matches_df['season'].astype('string')

# Season Mapping
season_mapping = {
    '2007/08':'2008',
    '2009/10':'2010',
    '2020/21':'2020'
}

# Replacing with data
matches_df['season'] = matches_df['season'].replace(season_mapping)

# Removing leftover spaces
matches_df['season'] = matches_df['season'].str.strip()

# String -> Int Conversion
matches_df['season'] = pd.to_numeric(matches_df['season'], errors='coerce').astype('Int64')

In [33]:
# Converting date column to datetime 
matches_df['date'] = pd.to_datetime(matches_df['date'], errors='coerce')

In [34]:
summary = matches_df.groupby('season')['date'].agg(['min','max','count']).sort_index()
summary['calender_years'] = matches_df.groupby('season')['date'].apply(lambda x: sorted(x.dt.year.dropna().unique().astype(int)))
summary

              min        max  count calender_years
season
2008   2008-04-18 2008-06-01     58         [2008]
2009   2009-04-18 2009-05-24     57         [2009]
2010   2010-03-12 2010-04-25     60         [2010]
2011   2011-04-08 2011-05-28     73         [2011]
2012   2012-04-04 2012-05-27     74         [2012]
2013   2013-04-03 2013-05-26     76         [2013]
2014   2014-04-16 2014-06-01     60         [2014]
2015   2015-04-08 2015-05-24     59         [2015]
2016   2016-04-09 2016-05-29     60         [2016]
2017   2017-04-05 2017-05-21     59         [2017]
2018   2018-04-07 2018-05-27     60         [2018]
2019   2019-03-23 2019-05-12     60         [2019]
2020   2020-09-19 2020-11-10     60         [2020]
2021   2021-04-09 2021-10-15     60         [2021]
2022   2022-03-26 2022-05-29     74         [2022]
2023   2023-03-31 2023-05-29     74         [2023]
2024   2024-03-22 2024-05-26     71         [2024]
2025   2025-03-22 2025-06-03     74         [2025]
2026   2026-03-28 2026-05-01     43         [2026]

In [35]:
matches_df.dtypes

match_id                    int64
date               datetime64[ns]
city                       object
venue                      object
team1                      object
team2                      object
toss_winner                object
toss_decision              object
winner                     object
result_type                object
player_of_match            object
season                      Int64
event_name                 object
match_type                 object
gender                     object
overs                       int64
balls_per_over              int64
team1_won                   int64
toss_winner_won             int64
dtype: object

In [36]:
# Changing Object -> String Datatype
object_col = matches_df.select_dtypes(include=['object']).columns
matches_df[object_col] = matches_df[object_col].astype('string')

In [37]:
# Missing values per column
missing_counts = matches_df.isna().sum()
missing_counts[missing_counts>0]

city               51
winner             25
player_of_match     9
dtype: int64

In [38]:
# Missing cities filling
missing_cities = matches_df[matches_df['city'].isna()][['venue','city']].drop_duplicates()
missing_cities

                                   venue  city
180  Dubai International Cricket Stadium  <NA>
182              Sharjah Cricket Stadium  <NA>

In [39]:
city_name = matches_df['venue'].astype(str).str.split().str[0]
matches_df['city'] = np.where(matches_df['city'].isna(), city_name, matches_df['city'])

In [40]:
matches_df['city'].isna().sum()

np.int64(0)

In [41]:
# Filling missing record of winner column
matches_df['winner'] = matches_df['winner'].fillna('No result')

In [42]:
# Filling missing record of player_of_match column
matches_df['player_of_match'] = matches_df['player_of_match'].fillna('None')

In [43]:
team_mapping = {
    'Deccan Chargers':'Sunrisers Hyderabad',
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab':'Punjab Kings',
    'Rising Pune Supergiants':'Rising Pune Supergiant',
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru'
}

team_col = ['team1','team2','toss_winner','winner']

for col in team_col:
    if col in matches_df.columns:
        matches_df[col] = matches_df[col].astype(str).str.strip()
        matches_df[col] = matches_df[col].replace(team_mapping)

In [65]:
matches_df.to_csv('ipl_matches_cleaned.csv', index = False)

# Analysis

In [44]:
ipl_df = pd.merge(deliveries_df, matches_df.drop(columns = ['date','city','venue','team1','team2','toss_winner','toss_decision','season']), left_on = 'match_id', right_on = 'match_id')

In [45]:
ipl_df

,match_id,date,season,venue,city,innings,batting_team,bowling_team,over,ball_in_over,...,winner,result_type,player_of_match,event_name,match_type,gender,overs,balls_per_over,team1_won,toss_winner_won
0,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,1,...,Sunrisers Hyderabad,"['by', 'winner']",Yuvraj Singh,Indian Premier League,T20,male,20,6,1,0
1,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,2,...,Sunrisers Hyderabad,"['by', 'winner']",Yuvraj Singh,Indian Premier League,T20,male,20,6,1,0
2,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,3,...,Sunrisers Hyderabad,"['by', 'winner']",Yuvraj Singh,Indian Premier League,T20,male,20,6,1,0
3,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,4,...,Sunrisers Hyderabad,"['by', 'winner']",Yuvraj Singh,Indian Premier League,T20,male,20,6,1,0
4,1082591,2017-04-05,2017,"Rajiv Gandhi International Stadium, Uppal",Hyderabad,1,Sunrisers Hyderabad,Royal Challengers Bengaluru,0,5,...,Sunrisers Hyderabad,"['by', 'winner']",Yuvraj Singh,Indian Premier League,T20,male,20,6,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288221,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bengaluru,Sunrisers Hyderabad,19,2,...,Sunrisers Hyderabad,"['by', 'winner']",BCJ Cutting,Indian Premier League,T20,male,20,6,0,1
288222,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bengaluru,Sunrisers Hyderabad,19,3,...,Sunrisers Hyderabad,"['by', 'winner']",BCJ Cutting,Indian Premier League,T20,male,20,6,0,1
288223,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bengaluru,Sunrisers Hyderabad,19,4,...,Sunrisers Hyderabad,"['by', 'winner']",BCJ Cutting,Indian Premier League,T20,male,20,6,0,1
288224,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bengaluru,Sunrisers Hyderabad,19,5,...,Sunrisers Hyderabad,"['by', 'winner']",BCJ Cutting,Indian Premier League,T20,male,20,6,0,1
288225,981019,2016-05-29,2016,M Chinnaswamy Stadium,Bangalore,2,Royal Challengers Bengaluru,Sunrisers Hyderabad,19,6,...,Sunrisers Hyderabad,"['by', 'winner']",BCJ Cutting,Indian Premier League,T20,male,20,6,0,1

In [46]:
ipl_df.shape

(288226, 44)

In [47]:
ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288226 entries, 0 to 288225
Data columns (total 44 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   match_id           288226 non-null  int64
 1   date               288226 non-null  datetime64[ns]
 2   season             288226 non-null  Int64
 3   venue              288226 non-null  string
 4   city               288226 non-null  object
 5   innings            288226 non-null  int64
 6   batting_team       288226 non-null  object
 7   bowling_team       288226 non-null  object
 8   over               288226 non-null  int64
 9   ball_in_over       288226 non-null  int64
 10  ball_number        288226 non-null  int64
 11  batter             288226 non-null  string
 12  bowler             288226 non-null  string
 13  non_striker        288226 non-null  string
 14  batter_runs        288226 non-null  int64
 15  extra_runs         288226 non-null  int64
 16  total_runs         288226 non-null  int64
 17  wides              288226 non-null  int64
 18  noballs            288226 non-null  int64
 19  byes               288226 non-null  int64
 20  legbyes            288226 non-null  int64
 21  penalty            288226 non-null  int64
 22  is_wicket          288226 non-null  int64
 23  wicket_player_out  288226 non-null  string
 24  wicket_kind        288226 non-null  string
 25  match_winner       288226 non-null  object
 26  toss_winner        288226 non-null  object
 27  toss_decision      288226 non-null  string
 28  team1              288226 non-null  object
 29  team2              288226 non-null  object
 30  is_powerplay       288226 non-null  int64
 31  is_middle_overs    288226 non-null  int64
 32  is_death_overs     288226 non-null  int64
 33  batting_team_won   288226 non-null  int64
 34  winner             288226 non-null  object
 35  result_type        288226 non-null  string
 36  player_of_match    288226 non-null  string
 37  event_name         288226 non-null  string
 38  match_type         288226 non-null  string
 39  gender             288226 non-null  string
 40  overs              288226 non-null  int64
 41  balls_per_over     288226 non-null  int64
 42  team1_won          288226 non-null  int64
 43  toss_winner_won    288226 non-null  int64
dtypes: Int64(1), datetime64[ns](1), int64(22), object(8), string(12)
memory usage: 97.0+ MB

In [48]:
# Adding year column for batsman analysis
#ipl_df['year'] = ipl_df['date'].dt.year

# Grouping by year and total runs of batter per year
runs_per_year = (
    ipl_df.groupby(['season','batter'])
    .agg(
        total_runs = ('batter_runs','sum'),
        total_innings = ('match_id', 'nunique') 
    ).reset_index() 
)

runs_per_year

      season             batter  total_runs  total_innings
0       2008           A Chopra          42              5
1       2008           A Kumble          13              4
2       2008           A Mishra          37              3
3       2008           A Mukund           0              1
4       2008            A Nehra           3              3
...      ...                ...         ...            ...
2923    2026            VR Iyer          41              2
2924    2026           WG Jacks          46              1
2925    2026  Washington Sundar         169              9
2926    2026        XC Bartlett          11              1
2927    2026        YBK Jaiswal         312             10

[2928 rows x 4 columns]

In [49]:
# Orange Cap Winner
top_1 = (
    runs_per_year.sort_values(['season','total_runs'], ascending = [True,False]).groupby('season').head(1)
)
top_1

      season           batter  total_runs  total_innings
115     2008         SE Marsh         616             11
229     2009        ML Hayden         572             12
446     2010     SR Tendulkar         618             15
502     2011         CH Gayle         608             12
684     2012         CH Gayle         733             14
910     2013       MEK Hussey         733             17
1088    2014       RV Uthappa         660             16
1148    2015        DA Warner         562             14
1383    2016          V Kohli         973             16
1422    2017        DA Warner         641             14
1594    2018    KS Williamson         735             17
1694    2019        DA Warner         692             12
1866    2020         KL Rahul         676             14
2051    2021       RD Gaikwad         635             16
2144    2022       JC Buttler         863             17
2423    2023     Shubman Gill         890             17
2606    2024          V Kohli         741             15
2640    2025  B Sai Sudharsan         759             15
2840    2026         KL Rahul         433              9

In [50]:
# Bowler Analytics

In [59]:
# Bowler runs
ipl_df['bowler_runs'] = ipl_df['batter_runs'] + ipl_df['wides'] + ipl_df['noballs']

# Total ball bowled
ipl_df['legal_ball'] = ipl_df['wides'].fillna(0).eq(0) & ipl_df['noballs'].fillna(0).eq(0)

# Bowler wickets
bowler_wickets = ['caught', 'bowled', 'lbw', 'caught and bowled', 'hit wicket']
ipl_df['is_bowler_wicket'] = ipl_df['wicket_kind'].isin(bowler_wickets).astype(int)

# Grouping & Aggregating
bowler_stats = ipl_df.groupby('bowler').agg(
    matches = ('match_id', 'nunique'),
    legal_balls = ('legal_ball', 'sum'),
    bowler_runs = ('bowler_runs', 'sum'),
    bowler_wicket = ('is_bowler_wicket', 'sum')
).reset_index()

In [60]:
# Calculating bowler average
bowler_stats['bowling_average'] = bowler_stats['bowler_runs'] / bowler_stats['bowler_wicket']

# Calculating bowler strike rate
bowler_stats['bowling_strike_rate'] = bowler_stats['legal_balls'] / bowler_stats['bowler_wicket']

# Calculating bowler economy
bowler_stats['economy_rate'] = bowler_stats['bowler_runs'] / (bowler_stats['legal_balls'] / 6)

# Rounding for minimalistic & clean appearance 
bowler_stats = bowler_stats.round({'bowling_average': 2, 'bowling_strike_rate': 2, 'economy_rate': 2})

In [61]:
bowler_stats

,bowler,matches,legal_balls,bowler_runs,bowler_wicket,bowling_average,bowling_strike_rate,economy_rate
0,A Ashish Reddy,20,262,396,18,22.00,14.56,9.07
1,A Badoni,8,41,63,4,15.75,10.25,9.22
2,A Chandila,12,234,242,9,26.89,26.00,6.21
3,A Choudhary,5,101,144,5,28.80,20.20,8.55
4,A Dananjaya,1,24,47,0,inf,inf,11.75
...,...,...,...,...,...,...,...,...
563,Yash Thakur,21,443,770,25,30.80,17.72,10.43
564,Yudhvir Singh,9,138,253,8,31.62,17.25,11.00
565,Yuvraj Singh,73,869,1077,32,33.66,27.16,7.44
566,Z Khan,99,2200,2782,102,27.27,21.57,7.59
567,Zeeshan Ansari,10,203,333,6,55.50,33.83,9.84